#!/bin/bash

if [[ -z "$1" || -z "$2" ]]; then
  echo "Usage: $0 <username> <cid>"
  exit 1
fi

# First parameter is username
username=$1

# Second parameter is cid of username
cid=$2

# Random uuid
uuid=$(curl -s "uuid4.com/?count=1")

# Generate referer URL
ref="https://www.etoro.com/people/$username/stats"

# Generate data source URL
url="https://www.etoro.com/sapi/rankings/cid/$cid/rankings/?Period=OneYearAgo&client_request_id=$uuid"

# Set user-agent
ua=Chrome

# Accept JSON header
accept="accept: application/json"

# Fetch data and print to stdout
curl -sL -H "$accept" -A "$ua" -e "$ref" "$url"

# Throttle
sleep 10
